<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitb8405cae070bbc1e1225ce6e891ef364
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('WPUM\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \WPUM\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitb8405cae070bbc1e1225ce6e891ef364', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \WPUM\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitb8405cae070bbc1e1225ce6e891ef364', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\WPUM\Composer\Autoload\ComposerStaticInitb8405cae070bbc1e1225ce6e891ef364::getInitializer($loader));

        $loader->register(true);

        $filesToLoad = \WPUM\Composer\Autoload\ComposerStaticInitb8405cae070bbc1e1225ce6e891ef364::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
